FROM python:3.11
WORKDIR /app

COPY ./python-deps-image/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

CMD ["python", "-c", "import numpy as np; print('numpy', np.__version__)"]
